name: Build Docker Container
echo "##active_line2##"

echo "##active_line3##"
on:
echo "##active_line4##"
  push:
echo "##active_line5##"
    branches: [ main ]
echo "##active_line6##"

echo "##active_line7##"
jobs:
echo "##active_line8##"
  build:
echo "##active_line9##"
    runs-on: ubuntu-latest
echo "##active_line10##"

echo "##active_line11##"
    steps:
echo "##active_line12##"
    - uses: actions/checkout@v2
echo "##active_line13##"

echo "##active_line14##"
    - name: Set up Docker Buildx
echo "##active_line15##"
      uses: docker/setup-buildx-action@v1
echo "##active_line16##"

echo "##active_line17##"
    - name: Build and push
echo "##active_line18##"
      uses: docker/build-push-action@v2
echo "##active_line19##"
      with:
echo "##active_line20##"
        context: .
echo "##active_line21##"
        push: false
